#!/bin/bash
set -euo pipefail

if [[ "$(arch)" == "aarch64" ]]; then
  arch="arm64"
else
  arch="amd64"
fi

plugin=${BUILDKITE_PLUGINS:-""}
version=v2.1.1
#version=$(echo $plugin | sed -e 's/.*monorepo-diff-buildkite-plugin//' -e 's/\".*//')
repo="https://github.com/chronotc/monorepo-diff-buildkite-plugin"
executable="monorepo-diff-buildkite-plugin-darwin-${arch}"
test_mode="${BUILDKITE_PLUGIN_MONOREPO_DIFF_BUILDKITE_PLUGIN_TEST_MODE:-false}"

echo "the plugin: ${plugin}"

#if [ -z ${version} ]; then
#  url=${repo}/releases/latest/download/${executable}
#else
  url=${repo}/releases/download/#{version:1}/${executable}
#fi

echo "downloading the binary :)"

if [[ "$test_mode" == "false" ]]; then
  echo ${url}
  curl -Lf -o ${executable} $url && chmod +x ${executable}
fi

echo "executing the binary <>"

./${executable}

echo "finished executing the binary"
